const data = {
  products: [
    {
      name: 'party wear dress',
      category: 'kids wear',
      image: '/images/img16.jpeg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Able made',
      rating: 4.5,
      numReviews: 10,
      description: 'Quality of dress is good!.',
    },
    {
      name: 'women wedding dress',
      category: 'wedding dress',
      image: '/images/img17.jpeg',
      price: 250,
      countInStock: 2,
      brand: 'Adore me',
      rating: 4.0,
      numReviews: 10,
      description: 'Quality of dress is awesome!',
    },
    {
      name: 'Apple iphone',
      category: 'mobile',
      image: '/images/iphone2.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Mufti',
      rating: 4.5,
      numReviews: 14,
      description: 'Elevate the quaility of mobile and specifications is good.',
    },
    {
      name: 'Bennetton Denim Pant',
      category: 'Pants',
      image: '/images/pant3.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Bennetton',
      rating: 4.5,
      numReviews: 10,
      description: 'Feel the ultimate comfort and style in Bennetton Denim Pants – your go-to choice for casual chic vibes!',
    },
    {
      name: 'ASUS Zen Mobile',
      category: 'Mobile',
      image: '/images/mobile1.jpg',
      price: 65,
      countInStock: 5,
      brand: 'ASUS',
      rating: 4.5,
      numReviews: 10,
      description: 'Sleek design, powerful performance. Capture lifes moments with precision. Your everyday companion for seamless connectivity and style.',
    },
    {
      name: 'Apple XR Iphone',
      category: 'Mobile',
      image: '/images/iphone1.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'Meet the Apple XR iPhone – sleek design, stunning display, and powerful performance in one pocket-sized marvel. Elevate your experience!',
    },
    {
      name: 'shirt',
      category: 'shirts',
      image: '/images/shirt2.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Gap',
      rating: 4.5,
      numReviews: 10,
      description: 'Quality is good!',
    },
    {
      name: 'Apple mac Book',
      category: 'Laptop',
      image: '/images/img3.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'Meet the sleek and powerful Apple MacBook – your creative companion with stunning design and lightning-fast performance. Elevate your experience!',
    },

    {
      name: 'pants',
      category: 'pants',
      image: '/images/pant2.jpg',
      price: 65,
      countInStock: 5,
      brand: 'monsoon',
      rating: 4.5,
      numReviews: 10,
      description: 'quaility is good',
    },
  ],
};
export default data;
